blank_issues_enabled: false
contact_links:
  - name: Report issues in Avalonia Accelerate repository
    url: https://github.com/AvaloniaUI/Accelerate/issues/new/choose
    about: Please file bugs and feature requests in the Accelerate repository.
